version: '3.8'

services:
  docker:
    image: docker:dind
    container_name: jenkins-docker
    restart: on-failure
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

  jenkins:
    build: .
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      # - CASC_JENKINS_CONFIG=/var/jenkins_home/casc
      # - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Djenkins.CLI.disabled=true
      # - ADMIN_USER=${ADMIN_USER:-admin}
      # - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      # - ./casc:/var/jenkins_home/casc:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:
