jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${ADMIN_USER:-admin}"
          password: "${ADMIN_PASSWORD:-admin}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false